"""add_tenant_schema_and_rls

Revision ID: 5a477e11f2af
Revises: 2b0d51534de2
Create Date: 2026-05-16 09:29:54.735926

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "5a477e11f2af"
down_revision: Union[str, None] = "2b0d51534de2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop legacy tables (no tenant_id) before recreating with tenant_id
    op.execute("DROP TABLE IF EXISTS hypothesis_records CASCADE")
    op.execute("DROP TABLE IF EXISTS reasoning_traces CASCADE")
    op.execute("DROP TABLE IF EXISTS research_tasks CASCADE")
    op.execute("DROP TABLE IF EXISTS workflow_records CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hypothesis_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("topic", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=True),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reasoning_traces",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("operation", sa.String(length=100), nullable=False),
        sa.Column("input_hash", sa.String(length=16), nullable=False),
        sa.Column("output_summary", sa.Text(), nullable=False),
        sa.Column("agent_id", sa.String(length=36), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "research_tasks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("results", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workflow_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("goal", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("sub_questions", sa.JSON(), nullable=True),
        sa.Column("results", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute("DROP TABLE IF EXISTS tenant_usage CASCADE")
    op.execute("DROP TABLE IF EXISTS subscriptions CASCADE")
    op.execute("DROP TABLE IF EXISTS projects CASCADE")
    op.execute("DROP TABLE IF EXISTS api_keys CASCADE")
    op.alter_column(
        "tenants", "domain", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "tenants",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "role",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        existing_server_default=sa.text("'member'::character varying"),
    )
    op.drop_constraint(op.f("users_tenant_id_email_key"), "users", type_="unique")

    # RLS: research_tasks
    op.execute("ALTER TABLE research_tasks ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE research_tasks FORCE ROW LEVEL SECURITY;")
    op.execute("""
        CREATE POLICY tenant_isolation ON research_tasks
        FOR ALL
        USING (tenant_id = current_setting('app.tenant_id', true)::UUID);
    """)

    # RLS: workflow_records
    op.execute("ALTER TABLE workflow_records ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE workflow_records FORCE ROW LEVEL SECURITY;")
    op.execute("""
        CREATE POLICY tenant_isolation ON workflow_records
        FOR ALL
        USING (tenant_id = current_setting('app.tenant_id', true)::UUID);
    """)

    # RLS: hypothesis_records
    op.execute("ALTER TABLE hypothesis_records ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE hypothesis_records FORCE ROW LEVEL SECURITY;")
    op.execute("""
        CREATE POLICY tenant_isolation ON hypothesis_records
        FOR ALL
        USING (tenant_id = current_setting('app.tenant_id', true)::UUID);
    """)

    # RLS: reasoning_traces
    op.execute("ALTER TABLE reasoning_traces ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE reasoning_traces FORCE ROW LEVEL SECURITY;")
    op.execute("""
        CREATE POLICY tenant_isolation ON reasoning_traces
        FOR ALL
        USING (tenant_id = current_setting('app.tenant_id', true)::UUID);
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON research_tasks;")
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON workflow_records;")
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON hypothesis_records;")
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON reasoning_traces;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("users_tenant_id_email_key"),
        "users",
        ["tenant_id", "email"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "users",
        "role",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
        existing_server_default=sa.text("'member'::character varying"),
    )
    op.alter_column(
        "tenants",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "tenants", "domain", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.create_table(
        "api_keys",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "key_hash", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("prefix", sa.VARCHAR(length=8), autoincrement=False, nullable=True),
        sa.Column(
            "permissions",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "last_used_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "expires_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("api_keys_tenant_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("api_keys_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("api_keys_pkey")),
        sa.UniqueConstraint(
            "key_hash",
            name=op.f("api_keys_key_hash_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("tenant_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "data",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("projects_tenant_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("projects_pkey")),
    )
    op.create_table(
        "subscriptions",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "plan_id", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "status",
            sa.VARCHAR(length=20),
            server_default=sa.text("'active'::character varying"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "current_period_start",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "current_period_end",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "canceled_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "payment_method",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("subscriptions_tenant_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("subscriptions_pkey")),
    )
    op.create_table(
        "tenant_usage",
        sa.Column("tenant_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column(
            "metric_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "units_consumed",
            sa.BIGINT(),
            server_default=sa.text("'0'::bigint"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "date", "metric_name", name=op.f("tenant_usage_pkey")
        ),
    )
    op.drop_table("workflow_records")
    op.drop_table("research_tasks")
    op.drop_table("reasoning_traces")
    op.drop_table("hypothesis_records")
    # ### end Alembic commands ###
