"""add_memory_outbox

Revision ID: 6e45cc784dfa
Revises: 5a477e11f2af
Create Date: 2026-05-18 01:02:38.087541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.memory.schema

revision: str = '6e45cc784dfa'
down_revision: Union[str, None] = '5a477e11f2af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_outbox',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', src.memory.schema.GUID(), nullable=False),
    sa.Column('entry_id', sa.String(length=36), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memory_outbox')
    # ### end Alembic commands ###
