"""make_tenant_domain_nullable

Revision ID: 956bea82e867
Revises: 6e45cc784dfa
Create Date: 2026-05-18 01:21:35.146719

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "956bea82e867"
down_revision: Union[str, None] = "6e45cc784dfa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tenants", "domain", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tenants", "domain", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    # ### end Alembic commands ###
