"""Generate new RegulatoryGuard rules from adversarial prompts that slipped past the guard.

Each missed attack prompt is mined for significant keyword patterns. New patterns are
written as a YAML rule file compatible with RegulatoryGuard so they take effect on
the next guard instantiation — no restart required.
"""

import logging
import re
from pathlib import Path

import yaml

logger = logging.getLogger(__name__)

_CORPUS_PATH = Path(__file__).parent / "red_team_corpus.yaml"
_LEARNED_RULES_PATH = Path(__file__).parent / "rules" / "learned_rules.yaml"

_STOP_WORDS = frozenset(
    {
        "a", "an", "the", "and", "or", "but", "in", "on", "at", "to", "for",
        "of", "with", "is", "are", "was", "be", "by", "this", "that", "from",
        "it", "its", "as", "all", "my", "your", "our", "now", "not", "no",
        "me", "i", "you", "we", "they", "he", "she", "have", "has", "do",
        "does", "did", "will", "would", "can", "could", "should", "about",
        "any", "some", "more", "than", "just", "into", "out", "up", "how",
    }
)

# Minimum character length for a keyword to be worth indexing
_MIN_KEYWORD_LEN = 5


def _extract_keywords(text: str) -> list[str]:
    """Extract significant single-word keywords from an adversarial prompt."""
    words = re.findall(r"[a-zA-Z]{3,}", text.lower())
    return [
        w for w in dict.fromkeys(words)  # dedupe, preserve order
        if w not in _STOP_WORDS and len(w) >= _MIN_KEYWORD_LEN
    ][:6]  # cap at 6 per prompt


class ChaosRuleGenerator:
    """Mines missed attack prompts for keyword patterns and persists them as new rules.

    Writes to ``src/security/rules/learned_rules.yaml`` in a format compatible
    with RegulatoryGuard. The guard auto-loads this file on next instantiation,
    so learned rules become active without any code change or restart.
    """

    def __init__(
        self,
        corpus_path: Path = _CORPUS_PATH,
        learned_rules_path: Path = _LEARNED_RULES_PATH,
    ) -> None:
        self._corpus_path = corpus_path
        self._learned_path = learned_rules_path

    def _load_attack_prompts(self) -> dict[str, dict]:
        """Return {id: entry} from corpus attack_prompts section."""
        if not self._corpus_path.exists():
            return {}
        with open(self._corpus_path, encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}
        return {e["id"]: e for e in data.get("attack_prompts", [])}

    def _load_learned_rules(self) -> list[dict]:
        if not self._learned_path.exists():
            return []
        with open(self._learned_path, encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}
        return data.get("rules", [])

    def _existing_keywords(self, learned: list[dict]) -> frozenset[str]:
        kws: set[str] = set()
        for rule in learned:
            kws.update(rule.get("keywords", []))
        return frozenset(kws)

    def generate_and_persist(self, missed_ids: list[str]) -> int:
        """Mine missed attack prompts and write new keyword rules.

        Returns the count of new rules actually written.
        """
        if not missed_ids:
            return 0

        corpus = self._load_attack_prompts()
        existing_rules = self._load_learned_rules()
        known_keywords = self._existing_keywords(existing_rules)

        counter = len(existing_rules) + 1
        new_rules: list[dict] = []

        for mid in missed_ids:
            entry = corpus.get(mid)
            if not entry:
                continue
            keywords = [
                kw for kw in _extract_keywords(entry.get("text", ""))
                if kw not in known_keywords
            ]
            if not keywords:
                continue
            rule = {
                "id": f"LEARNED-{counter:03d}",
                "severity": entry.get("severity", "HIGH"),
                "message": (
                    f"Learned adversarial pattern ({entry.get('category', 'unknown')}) "
                    f"— generated by ChaosAgent from missed id={mid}"
                ),
                "domains": ["all"],
                "keywords": keywords,
                "enabled": True,
            }
            new_rules.append(rule)
            known_keywords = known_keywords | frozenset(keywords)
            counter += 1
            logger.info(
                "chaos_rule_generator.new_rule id=%s keywords=%s",
                rule["id"],
                keywords,
            )

        if not new_rules:
            return 0

        all_rules = existing_rules + new_rules
        self._learned_path.parent.mkdir(parents=True, exist_ok=True)
        with open(self._learned_path, "w", encoding="utf-8") as f:
            yaml.dump(
                {"rules": all_rules},
                f,
                allow_unicode=True,
                default_flow_style=False,
                sort_keys=False,
            )

        logger.info(
            "chaos_rule_generator.persist wrote=%d total_learned=%d",
            len(new_rules),
            len(all_rules),
        )
        return len(new_rules)

    def rule_count(self) -> int:
        return len(self._load_learned_rules())

    def all_rules(self) -> list[dict]:
        return self._load_learned_rules()
